{% set name = "Flask-Executor" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: ddb51b9e10f0fbfcff6c2386a5d92957402b7c81b7614eb1f3c77be64bcfd684

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - flask

test:
  imports:
    - flask_executor
    - flask_executor.futures
    - flask_executor.helpers

about:
  home: https://github.com/dchevell/flask-executor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Adds concurrent.futures support to Flask

  description: |
    Flask-Executor is an easy to use wrapper for the concurrent.futures module that lets you initialise and configure executors via common Flask application patterns. It's a great way to get up and running fast with a lightweight in-process task queue.
  doc_url: https://flask-executor.readthedocs.io/
  dev_url: https://github.com/dchevell/flask-executor

extra:
  recipe-maintainers:
    - abloemert
