{% set name = "Flask-Executor" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4bc113def5d9f1c7ff272ff7ba09f843468eab80469bdbd21625a111b2c8ae7b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - flask

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_executor
    - flask_executor.futures
    - flask_executor.helpers

about:
  home: https://github.com/dchevell/flask-executor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Adds concurrent.futures support to Flask

  description: |
    Flask-Executor is an easy to use wrapper for the concurrent.futures module that lets you initialise and configure executors via common Flask application patterns. It's a great way to get up and running fast with a lightweight in-process task queue.
  doc_url: https://flask-executor.readthedocs.io/
  dev_url: https://github.com/dchevell/flask-executor

extra:
  recipe-maintainers:
    - abloemert
